### ISSUE TITLE
Add type validation to task execution engine

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#101]
Can be invoked independently of running a task
Is run automatically prior to running any task

Type  validation is validating that types for input and output match and are consistently with expected plug-in interfaces

## Definition of Done
- [x] Type Validation
- [x] Update documentation
- [x] Unit Tests exercising validation

**Comment by chisholm** [comment]
Decisions made at the in-person working session on 12/6/2022:

We will try to support limited structural typing, i.e. have the ability to define inner structure of types and check values against this.  Structural type definition will be limited to:

- dicts (list all properties, with a type for each one)
- lists (a list of variable length, of homogenous element type)
- tuples (a list of fixed length which can have heterogenous element types)

We will not support defining optional components of these types.  E.g. treat all declared dict properties as required.  If someone wants to "omit" a property, they can include it with a null value.

We will not support subtyping, at least with these with these more complex, structural types.  That would add too much complexity (e.g. you'd have to think about type covariance, contravariance, invariance).

The goal is to enable type validation of ad-hoc compositions of task plugin outputs, which would ordinarily not have an assigned type, since the value does not simply come from a single task plugin output (which would have an associated type).

**Comment by chisholm** [comment]
Decisions made on 1/11/2023:

Add a variant of a mapping structure where the key type and value type are described, but property names are not enumerated.  This supports describing inputs for task plugins like `log_parameters`, which should allow any parameters to be logged, not just those limited to an enumerated list.  Legal key types should include strings and integers only (for now).

Other Notes:

Integration steps still to do include:
- Update JSON-Schema for declarative experiment description YAML structure to include type information
- Add type definition validation which is impossible/awkward to do via schema
- Add type validation to the overall validation process
- Use the required/optional settings for task plugin inputs to do additional validation of task invocations, ensuring required inputs have been provided in the invocations
- Add documentation of the type system

Type validation sequence will need to be:
1. Schema validate  (Errors will be categorized as "schema")
2. Do handwritten checks  (Errors will be categorized as "semantic")
3. Build type registry
4. Do type validation (Errors will be categorized as "type")

I consider only step 4 to be "type validation".  Type validation is about validating *other* things on the basis of types, not validating the type definitions themselves.  One must have types before one can do type validation, so I think of steps 1-3 as preparatory/prerequisite.

**Comment by jkglasbrenner** [comment]
Closed by #131
