### ISSUE TITLE
Create a JWT prototype

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#222]
Create a JWT prototype using:
- https://pyjwt.readthedocs.io/
- https://python-jose.readthedocs.io/

Prototype can be a simple Flask application using Flask-login (can be fixed user/name password) that will demonstrate how to create and use JWT tokens for authorization. A single simple endpoint is all that is needed. Expanding off one of the existing tutorial examples should be sufficient. 

# Definition of Done
- [x] #258
- [x] Demonstrates secure/best practices for JWT use
- [x] Identify selection criteria for which library to use

**Comment by lbarbMITRE** [comment]
Hi! On the off chance I am not on call when you discuss this issue tomorrow, I wanted to do this write up to cover my progress. I believe this issue is complete, pending feedback of course. 

You can find my updated version of the flask prototype on my branch "lbarber-flask-authentication". It is located in the main dioptra directory under the folder "flask-prototype"

I completed the addition of JWT tokens to the api and integrated them into the existing endpoints (see /auth/login specifically). The login endpoint returns the signed JWT token, which can then be added to requests in the "x-access-token" header for authentication.

Changes:
- auth.py: added token generation to /auth/token, which now also returns token
- user.py: added load_user_from_request function to handle token validation and returns user to login manager
- __init.py__ : changed login manager to use request_loader instead of user_loader
- added vault for key and certificate storage
- started support for fully integrated https

I added the support for https for securely delivering the JWTs and for trying to follow best practices (from my research https seems to be sufficient for secure delivery). I haven't figured out how to fully integrate using https into the app without some refactoring (not sure if we want to for this prototype), however you can add these flags on the command line when running flask to enable it:
flask run --cert="proto/vault/cert.pem" --key="proto/vault/key.pem"

Feel free to leave comments/feedback here if I am not a part of the discussion!
