### ISSUE TITLE
 QueueNameResource has no put method

### ISSUE THREAD

**Issue by alexb1200** [usnistgov/dioptra#340]
**Describe the bug**
The docstring for QueueNameResource mentions being able to modify the queue but doesn't provide any method to. https://github.com/usnistgov/dioptra/blob/bab6efb5a3acd021428677a526502bfadb17616f/src/dioptra/restapi/queue/controller.py#L156

**Potential Solution**
A put method should be added similar to https://github.com/usnistgov/dioptra/blob/bab6efb5a3acd021428677a526502bfadb17616f/src/dioptra/restapi/queue/controller.py#L80C10-L80C10

**Comment by jkglasbrenner** [comment]
This is design choice instead of a bug. The PUT command in a RESTful API is expected to be idempotent, however allowing it in `QueueNameResource` violates that assumption.

To give an explicit example, let's imagine the queue is originally named `"foo"` and has the unique identifier `1`. Doing the following request two times in a row works without issue, and results in the same final state for the resource on the backend:

    PUT `/queue/1`, json={'name': 'bar'}  # No error, queue id=1 is renamed to 'bar'
    PUT `/queue/1`, json={'name': 'bar'}  # No error, queue id=1 still has the new name 'bar'

However, if we allow a PUT on `QueueNameResource`, we cannot do the same thing:

    PUT `/queue/name/foo`, json={'name': 'bar'}  # No error, queue name='foo' is renamed to 'bar'
    PUT `/queue/name/foo`, json={'name': 'bar'}  # Returns error, queue with name='foo' not found

Since it's not possible to keep the latter case idempotent, we do not allow it in the REST API.
