### ISSUE TITLE
[BUG] GUI- Plugins field missing when editing an entry point

### ISSUE THREAD

**Issue by mtrapnell-nist** [usnistgov/dioptra#549]
**Describe the bug**
The plugins field is present when creating an entry point, but it is missing during editing. 

**To Reproduce**
1. Create an entry point
2. Select that that entry point from the list and click Edit.
3. The Plugins field is now missing from the page and can't be edited.

**Expected behavior**
The Plugins field should be editable after an entry point is created.

**Screenshots**
![Entry Point- Create](https://github.com/user-attachments/assets/a57056cc-13a8-4dd7-a6f1-1a4fafaa6d14)

The Plugins label and drop down box is missing on the edit page:
![Entry Point- Edit page missing Plugins field](https://github.com/user-attachments/assets/b8b8d91e-8163-4b8c-80a1-206696174a7d)

**Desktop (please complete the following information):**
  - OS: macOS Sonoma 14.5
 - Browser: Firefox
 - Version: 128.0

**Comment by jkglasbrenner** [comment]
Closed by #532

**Comment by henrychoy** [comment]
@mtrapnell-nist That omission was actually intentional because the the create entrypoints endpoint accepts both plugins and queues, but the modify endpoint only has queues.  

There's the add plugin button on the entrypoints table, that doesn't completely work yet.  There's also a syncing that needs to happen between entrypoints and plugins that I need to include somehow in the UI.  So more to come on these two points.
