### ISSUE TITLE
Cannot install / run demo

### ISSUE THREAD

**Issue by piyush-an** [usnistgov/dioptra#76]
# Cannot install / run demo on local

## Steps to reproduce the bug
Following the [Installation Guide](https://pages.nist.gov/dioptra/getting-started/installation.html#installation-guide) and [Hello World!](https://pages.nist.gov/dioptra/tutorials/example-basic-mlflow-demo.html#hello-world) documentation.
1. Docker running
2. On Terminal
```bash
git clone https://github.com/usnistgov/dioptra.git
cd dioptra
git branch
# * main
git pull
conda env create --file environment.yml
conda activate dioptra
make pull-latest-hub pull-latest-ci pull-latest-testbed
```

## Resulting and expected behavior
```bash
make pull-latest-hub pull-latest-ci pull-latest-testbed
# make: *** No rule to make target `pull-latest-hub'.  Stop.

make pull-latest
# make: *** No rule to make target `pull-latest'.  Stop.

make demo
# make: *** No rule to make target `demo'.  Stop.
```
The Makefile does not include these task.

Observation:
The makefile was updated recently however the documentation seems to be off with the latest changes.
Even generated the doc locally but its same as in the website.

## System information
conda  4.9.2
docker 4.11.1 (84025)
## Operating system
MacOS

## Time (including time zone)
2022-08-09 20:12:59 EST

**Comment by jkglasbrenner** [comment]
Thank you @piyush-an and @aullahmitre for submitting your issue. The problem that you're encountering is due to the documentation being out-of-date, the `make pull-*` commands were used during internal development before the project was open-sourced and they have since been removed from the Makefile. The development team is actively working on a new approach to configuring and running the Dioptra containers on a single computer. We will be updating the documentation to reflect the change and also remove out-of-date and conflicting instructions like you've both reported. The progress is being tracked in #83. Tentatively we're aiming to have this update available by the end of December, and we encourage you to come back and try it out once it's merged!
