### ISSUE TITLE
Identifying new REST API endpoints

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#92]
## Notes

All of the features of MLFlow that Dioptra currently uses are integrated into a common REST API.

This includes:

- Model registry
- Job API
- Aggregating experiment results

**Comment by hbooth** [comment]
In order to properly control access and authorization we need to replace the existing used MLFlow functionality with new REST APIs that will include appropriate authorization and access and any required inputs for running.

To accomplish this we will need:
- A job context manager to replace the MLflow active session object
- New REST endpoints to replicate the MLFLow tracking and other apis indicated below
- A solution for uploading and retrieval of artifacts which respects access control (including jobs/tasks running on workers)



![Image](https://user-images.githubusercontent.com/10638455/205962876-5e9d646b-2e5a-457e-b9d8-e86c0371dbf4.png)




APIs currently used by Dioptra:

- [ ] ML Flow Tracking
- [ ] Run Metadata (Info about the run, Results)
- [ ] Artifacts Registry
- [ ] Model Registry

Additionally, all task plugins (and examples) which interact with MLFlow will require updates to use new API

**Comment by keithmanville** [comment]
stale
